### PR TITLE
Small updates to documentation/logging

### PR DESCRIPTION
**Pull request by PalminX**
Hi,

I am sorry I still don't know how to create good pull requests ;-)
This one contains some (spurious) changes from yesterday.

The main commits are the ones from today (2019-03-08):
* Cleaned up documentation and added examples
* Added logging of complete URLS (incl. query parameters)
* Added console log for missing iCloud directory
* Added your heatmap.html example

### CODE REVIEW

**Review by thoughtgap — APPROVED** [review]
Thanks!

**Review by thoughtgap — CHANGES_REQUESTED** [review]
Let's try this "Review Changes" feature 😄 

I like all of this expect the duration calculation. `timelineItem.startDate` and `timelineItem.endDate` are already parsed as `Date`, so instead of

```javascript
duration: displayTime(((new Date()).setTime(timelineItem.endDate.getTime() - timelineItem.startDate.getTime()))),
````

you could just go `duration: displayTime(timelineItem.endDate - timelineItem.startDate)`

Also I'd rename `displayTime()` to `displayDuration()`

**Comment by PalminX** [comment]
@thoughtgap, thanks for the comment about the duration calculation... it seems that I got so sidetracked by my experiments during the implementation that I missed that the final thing could be simplified so much ;-)

**Review by PalminX — COMMENTED** [review]
Hm, I still don't quite get this "Review changes" process on GitHub. I have now made a new commit on PalminX:master, which is not included in the review request.

**Review by PalminX — COMMENTED** [review]
But now, the changes include my new commit, with the proposed changes.

So, I think you could Approve now?

**Review by thoughtgap — APPROVED** [review]

**Pull request merged**
